AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'node_modules/**/*'
    - '.pryrc'

Bundler/OrderedGems:
  Enabled: false

Layout/AlignParameters:
  Exclude:
    - 'bin/*'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'bin/*'
    - 'spec/rails_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'
Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/RedundantBegin:
  Exclude:
    - 'bin/*'

Style/StderrPuts:
  Exclude:
    - 'bin/*'

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'config/environments/production.rb'
    - 'config/puma.rb'
    - 'db/schema.rb'
    - 'spec/controllers/home_controller_spec.rb'
    - 'spec/rails_helper.rb'
    - 'test/application_system_test_case.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'
